# Silence R CMD check for symbols that are not real bindings in the package
# namespace -- they are column names referenced via data.table's NSE, ggplot2
# aesthetics names (`tidy evaluation`), and a small number of internal helpers
# that R CMD check's static analyzer cannot resolve.

#' @importFrom data.table := .I .N .SD %chin%
#' @importFrom stats setNames dist end start offset
#' @importFrom utils head tail write.table
#' @importFrom grDevices palette
NULL

utils::globalVariables(c(
  "..cols", "..keep_af_cols", "..ord",
  ".GROUP_TMP", ".PROJ_GROUP", ".ROW_ID", ".data",
  ".draw_target", ".draw_unknown", ".gene_key", ".legend_group",
  ".manhattan_y_map",
  ".proj_class", ".proj_col_ref", ".proj_fill", ".proj_ref", ".proj_stroke",
  ".pt_col", ".pt_col_orig", ".pt_shape", ".pt_size", ".qc_status",
  ".row_id", ".x", ".y",
  "A1", "A2", "ALT_FREQS", "BETA",
  "CHR", "CHR0", "CHR_data", "CHR_ref", "CHR_tmp",
  "EAF", "EIGENVAL", "END",
  "FID", "F_MISS", "Gene", "Group",
  "ID", "IDM", "IID", "IID_USE",
  "N", "N_GENO", "N_MISS", "OBS_CT",
  "P", "POS", "POS_data", "POS_ref", "POS_tmp", "POSm1",
  "PP.diff", "PP.input", "P_tmp",
  "REASON", "REF", "SE", "SNP", "START",
  "V3", "V4", "Y", "Z",
  "a1", "a1_input", "a1_out", "a1_ref", "a2", "a2_ref",
  "ambiguous", "angle.degree",
  "beta0", "biotype", "biotype_raw",
  "c025", "c975", "cat_draw_order", "center0", "center_pos",
  "chr", "chr0", "chr_end", "chr_map", "chr_order",
  "chr_plot_color", "chr_start",
  "chrom", "chrom_col_use", "chrom_locus", "chrom_ref",
  "chroms_auto", "chroms_req", "color",
  "dedup_key", "default_snp2_color", "default_snp_color",
  "dir_col_lead_neg", "dir_col_lead_pos", "dir_col_neg", "dir_col_pos",
  "direction_size0", "drag_chrom_tick", "drag_chrom_vec",
  "draw", "draw_key", "ea",
  "end.degree", "ensg_id",
  "feature", "flank_color", "forced", "forced_threshold",
  "gene_id", "gene_name", "gene_prio", "gene_y",
  "group", "has_lead", "het_rate", "hjust", "hl", "hl_col",
  "i.a1_input", "i.input_idx", "i.markerID",
  "i_local", "idx", "input_idx", "input_order",
  "is_angle_270", "is_angle_90", "is_angle_repel_safe", "is_angle_zero",
  "is_causal", "is_focal", "is_lead", "is_lead_gene", "is_local",
  "j", "j_local",
  "label", "label_hjust", "label_ok", "label_text", "label_vjust",
  "ld", "ld1", "ld2",
  "lead.flank.hit", "lead.hit",
  "lead0", "leadSNP",
  "lead_col0", "lead_color_enabled", "lead_draw", "lead_id",
  "lead_label", "lead_label_col_std", "lead_pos", "lead_snp",
  "level", "line_dt",
  "locus", "locus_id", "locus_size",
  "markerID", "mid", "minP",
  "n", "n_causal_var", "n_indexSNP", "nea", "negLog10P",
  "p0", "palette_fac", "palette_key", "palette_lab",
  "pos", "pos0", "pos2", "pos_col_use", "pos_ref",
  "proxy", "proxyID",
  "ra1", "ra2", "radius",
  "ref_id", "ref_idx", "reference", "ridx", "row_id",
  "score", "score0", "se0",
  "shared_mode",
  "snp", "snp0", "snp1", "snp2", "snp_col_use", "snp_tmp",
  "span_end", "span_start", "strand", "summary_msg",
  "tend", "text_x", "text_y",
  "threshold_lines", "threshold_zero_mode",
  "tick", "track", "true_beta", "tss", "tstart", "txt_col", "type",
  "use_ceiling", "use_snp2", "use_y_rescale",
  "val", "width", "width.degree",
  "win_end", "win_start",
  "x", "x_data", "x_label", "x_tick",
  "xend", "xvalue",
  "y", "y.axis.title", "y.clip", "y.draw",
  "y.max0", "y.min", "y.raw",
  "y_bend", "y_ceiling0", "y_label", "y_plot",
  "y_rescale_at", "y_rescale_breaks", "y_text", "y_tip", "y_tmp",
  "ydraw", "yend", "yval", "z0",
  # ggplot/data.table aesthetics not caught by NSE rules
  "plot.alpha", "plot.color",
  "fill", "snp_tmp",
  "start.degree", "start.degree.chr",
  "obs_end", "obs_max", "obs_min",
  "center.degree", "gap.after",
  "flank_alpha", "flank_bp",
  "lead_border_color", "lead_color", "lead_color_arg",
  "lead_fill", "lead_group", "lead_highlight",
  "lead_label_arg", "lead_label_color", "lead_label_data",
  "lead_label_from_col", "lead_size", "lead_size_ceiling",
  "lead_size_main", "lead_stroke", "lead_stroke_arg",
  "linewidth",
  "pass_highlight",
  "plot_alpha", "plot_color", "plot_color_data",
  "point_shape", "shape_plot", "shared_r2", "size_plot",
  "track_first", "transcript_id",
  "y_anchor", "y_dir", "y_outside", "y_raw",
  "ydraw_data", "ydraw_plot", "ydraw_raw",
  "ld1_bin", "ld1_plot", "ld2_bin", "ld2_plot",
  "ld_group", "ld_legend",
  "score.outlier",
  # Second-pass additions discovered after the first declaration.
  ".", "..keep_afreq_cols", "..keep_cols", "..pc_names", "..req_fam",
  ".ID", ".LABEL_INPUT", ".OUTLIER_GROUP",
  ".REFERENCE_FLAG", ".REFERENCE_INPUT", ".REFERENCE_PC", ".SUBGROUP_INPUT",
  ".completeness", ".compute_y_breaks_reg",
  ".geneinfo_ensg", ".geneinfo_symbol",
  ".info_ensg", ".info_symbol",
  ".row_id_data", ".snp1", ".snp2",
  "A1.freq",
  "CHR.x", "CHR.y", "O_HOM", "PC_label",
  "POS.x", "POS.y", "PP.max",
  "alloc", "bin.id", "biotype_rank",
  "cap", "ceiling_data", "ceiling_marker",
  "chr_end.degree", "chr_num", "chr_offset", "chr_start.degree", "chr_width",
  "col_hex", "cum.prop", "cum.y",
  "dir_color", "dir_fill", "dir_fill_ce", "dir_size", "dir_stroke",
  "direction_color_inherit", "direction_draw", "direction_hit",
  "direction_lead_fill_override", "direction_sign",
  "drag_arrow_col", "drag_seg_col", "draw_id",
  "exon_number",
  "flank_highlight",
  "glyph", "group_color",
  "hjust_drag",
  "label.input", "label.max", "label_color_arg",
  "y_ceiling_plot"
), package = "gcanvas")
